### ISSUE TITLE
outer entities split in to halves based on type

### ISSUE THREAD

**Issue by Irfanbsse2060** [nbremer/d3-loom#3]
First of all its not issue i just need help. I have two types of outer entities. some outer entities belong to type A and some outer entities belong to type B.  i want to show type A entities on left halve and type B entities on right halve. is this possible with d3-loom?

**Comment by nbremer** [comment]
If the totals of the A and B are about a 50% split, then yes. You can either already the data in the correct order (first all of A then all of B), or you can use the `.sortGroups` option to sort the outer groups
